In [1]:
import numpy as np 

In [6]:
a = np.arange(0,100,2)
b = np.arange(0,100,2).

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [12]:
a = np.arange(100).reshape(4,5,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [13]:
np.save('a.npy',a)

In [16]:
b = np.load('a.npy')
print(np.equal(a,b))

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [20]:
np.random.rand(3,4,5)

array([[[0.31416362, 0.78282207, 0.99968979, 0.01123107, 0.20927635],
        [0.01341802, 0.7504267 , 0.76991174, 0.36690145, 0.64185197],
        [0.77146705, 0.10348688, 0.52409085, 0.14926598, 0.5911726 ],
        [0.38301849, 0.05973652, 0.24741681, 0.98051293, 0.49600987]],

       [[0.35402859, 0.94803865, 0.2041123 , 0.17949398, 0.64681813],
        [0.93256873, 0.51311857, 0.51670946, 0.2474734 , 0.96696891],
        [0.34585768, 0.66196157, 0.01250383, 0.10174266, 0.29319811],
        [0.86149725, 0.5636052 , 0.77464438, 0.83741824, 0.76827024]],

       [[0.97750019, 0.47918461, 0.01033265, 0.85158368, 0.33904078],
        [0.31816462, 0.6567957 , 0.88034031, 0.83137918, 0.38701449],
        [0.85557274, 0.66031127, 0.90446744, 0.14291438, 0.74313653],
        [0.73283985, 0.39368076, 0.55180387, 0.55902792, 0.73134087]]])

In [19]:
np.random.randn(3,4,5)

array([[[ 1.86875674e+00,  2.72089249e-01, -1.62890038e+00,
          4.88698981e-01, -1.20905660e+00],
        [-4.33254964e-01,  9.42484598e-01, -1.44326156e+00,
          5.61244845e-01,  2.05581011e+00],
        [ 7.53129014e-02,  1.90812925e-01,  1.45351388e-01,
         -5.31462491e-03,  2.25829240e-01],
        [ 2.06371252e-01,  2.76054211e-01, -4.52824701e-01,
         -2.09577869e-01,  4.57406912e-02]],

       [[-1.38244669e+00, -1.05068523e+00, -8.08113577e-02,
         -3.49701717e-02, -2.38063668e+00],
        [-1.96378333e+00, -1.36759049e+00, -4.77926724e-01,
          5.58737258e-01,  8.40295629e-01],
        [-5.93007058e-02, -1.11458278e+00,  2.49112424e+00,
         -4.06028005e-01, -1.30143274e+00],
        [ 4.29309644e-01, -1.60656018e+00, -6.51513716e-01,
          4.32265013e-01, -1.30244417e+00]],

       [[ 7.74594735e-01, -2.54915678e-01,  1.74717246e-03,
          1.59878098e+00,  3.66682210e-01],
        [ 1.92653894e-01, -8.23481017e-01,  1.01236679e+00,


In [21]:
np.random.randint(0,100,(3,4,5))

array([[[49, 52, 33, 42,  2],
        [59, 64, 30, 76, 18],
        [42, 82, 58, 39, 64],
        [95, 49, 41, 38, 66]],

       [[81, 90, 16, 74, 87],
        [20, 26, 76, 45, 60],
        [36, 46, 76, 71, 62],
        [89, 24, 15, 39, 22]],

       [[11, 94, 58, 36, 87],
        [44, 75, 26, 15, 85],
        [81, 58, 82, 71, 33],
        [27, 77, 86, 54, 91]]])

In [23]:
test1 = np.random.rand(3,4,5)
print('未调用随机数种子时候',test1)
np.random.seed(5)
test2 = np.random.rand(3,4,5)
print('调用随机数种子后',test2)
np.random.seed(5)
test3 = np.random.rand(3,4,5)
print('再一次调用随机数种子的结果',test3)

未调用随机数种子时候 [[[0.63535621 0.81190239 0.92668262 0.91262676 0.82481072]
  [0.09420273 0.36104842 0.03550903 0.54635835 0.79614272]
  [0.0511428  0.18866774 0.36547777 0.24429087 0.79508747]
  [0.35209494 0.63887768 0.49341505 0.58349974 0.93929935]]

 [[0.94354008 0.11169243 0.84355497 0.34602815 0.10082727]
  [0.38340907 0.5103548  0.96110308 0.37151262 0.01236941]
  [0.85970689 0.11111075 0.47833904 0.84998003 0.51473797]
  [0.44660783 0.80047642 0.02039138 0.57261865 0.41138362]]

 [[0.9851368  0.80140153 0.0539621  0.19047777 0.45241885]
  [0.70294208 0.33204815 0.3599832  0.92147057 0.95363051]
  [0.40768573 0.89857115 0.33025325 0.08273857 0.52671757]
  [0.66084439 0.89298429 0.96515755 0.76993268 0.75909912]]]
调用随机数种子后 [[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]
  [0.61174386 0.76590786 0.51841799 0.2968005  0.18772123]
  [0.08074127 0.7384403  0.44130922 0.15830987 0.87993703]
  [0.27408646 0.41423502 0.29607993 0.62878791 0.57983781]]

 [[0.5999292  0.26581912 0.2

In [29]:
np.random.seed()
a = np.arange(100).reshape(4,5,5)
print(a)
print('调用permutation后\n')
b = np.random.permutation(a)
print('b是随机打乱后的数组{} \n a是初始数组 {}'.format(b,a))
print('调用shuffle后\n')
np.random.shuffle(a)
print('a是初始数组 {}'.format(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
调用permutation后

b是随机打乱后的数组[[[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]] 
 a是初始数组 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 4

In [45]:
import matplotlib.pyplot as plt 
print('uniform(low,high,size)产生一个均匀分布的数组')
a = np.random.uniform(0,10,(3,3,4))
print(a,'\n')
print('normal(μ,σ,size)产生一个正态分布的数组')
b = np.random.normal(5,10,(3,3,4))
print(b)

uniform(low,high,size)产生一个均匀分布的数组
[[[9.89413674 5.39897874 9.55998013 0.76592501]
  [9.28129935 7.57292355 9.56749338 8.79866335]
  [7.9060995  7.56249251 8.50719662 8.6543727 ]]

 [[8.69980863 0.89804393 5.53434448 6.8653198 ]
  [8.02168006 7.50532017 8.58344748 2.44960786]
  [7.29087704 3.75203689 4.93468491 6.15320374]]

 [[2.59189971 7.70359792 8.32463435 8.29178183]
  [9.88864764 8.32112274 6.37018845 5.52161731]
  [1.78826102 8.89241698 3.10709625 2.89925039]]] 

normal(μ,σ,size)产生一个正态分布的数组
[[[ 11.4679588   -8.86188978 -14.73059752  -3.3117126 ]
  [ -8.73226325  27.29120988   3.91018156   0.0969557 ]
  [  1.45013445  12.51284971  -6.00659037  -4.13001938]]

 [[ -6.78578401   5.84869642  11.8444614   12.59164378]
  [  8.4278264   21.45573017  -6.33785163  24.81643987]
  [  8.73893644   2.95862982  -4.80887464  13.93729633]]

 [[  0.99106059  20.99427014 -12.27379075  17.04020572]
  [ -1.11467816  -2.6423889   -0.1661371   -3.21243236]
  [ 13.64014445  -8.27076843   4.82117687   2.

In [ ]:
np.sum()

np.mean()


In [66]:
a = np.arange(120).reshape(5,4,3,2)
print(np.sum(a,axis=1))
print(a)

[[[ 36  40]
  [ 44  48]
  [ 52  56]]

 [[132 136]
  [140 144]
  [148 152]]

 [[228 232]
  [236 240]
  [244 248]]

 [[324 328]
  [332 336]
  [340 344]]

 [[420 424]
  [428 432]
  [436 440]]]
[[[[  0   1]
   [  2   3]
   [  4   5]]

  [[  6   7]
   [  8   9]
   [ 10  11]]

  [[ 12  13]
   [ 14  15]
   [ 16  17]]

  [[ 18  19]
   [ 20  21]
   [ 22  23]]]


 [[[ 24  25]
   [ 26  27]
   [ 28  29]]

  [[ 30  31]
   [ 32  33]
   [ 34  35]]

  [[ 36  37]
   [ 38  39]
   [ 40  41]]

  [[ 42  43]
   [ 44  45]
   [ 46  47]]]


 [[[ 48  49]
   [ 50  51]
   [ 52  53]]

  [[ 54  55]
   [ 56  57]
   [ 58  59]]

  [[ 60  61]
   [ 62  63]
   [ 64  65]]

  [[ 66  67]
   [ 68  69]
   [ 70  71]]]


 [[[ 72  73]
   [ 74  75]
   [ 76  77]]

  [[ 78  79]
   [ 80  81]
   [ 82  83]]

  [[ 84  85]
   [ 86  87]
   [ 88  89]]

  [[ 90  91]
   [ 92  93]
   [ 94  95]]]


 [[[ 96  97]
   [ 98  99]
   [100 101]]

  [[102 103]
   [104 105]
   [106 107]]

  [[108 109]
   [110 111]
   [112 113]]

  [[114 115]
   [116 11

In [67]:
 a  

array([[[[  0,   1],
         [  2,   3],
         [  4,   5]],

        [[  6,   7],
         [  8,   9],
         [ 10,  11]],

        [[ 12,  13],
         [ 14,  15],
         [ 16,  17]],

        [[ 18,  19],
         [ 20,  21],
         [ 22,  23]]],


       [[[ 24,  25],
         [ 26,  27],
         [ 28,  29]],

        [[ 30,  31],
         [ 32,  33],
         [ 34,  35]],

        [[ 36,  37],
         [ 38,  39],
         [ 40,  41]],

        [[ 42,  43],
         [ 44,  45],
         [ 46,  47]]],


       [[[ 48,  49],
         [ 50,  51],
         [ 52,  53]],

        [[ 54,  55],
         [ 56,  57],
         [ 58,  59]],

        [[ 60,  61],
         [ 62,  63],
         [ 64,  65]],

        [[ 66,  67],
         [ 68,  69],
         [ 70,  71]]],


       [[[ 72,  73],
         [ 74,  75],
         [ 76,  77]],

        [[ 78,  79],
         [ 80,  81],
         [ 82,  83]],

        [[ 84,  85],
         [ 86,  87],
         [ 88,  89]],

        [[ 90,  91]

In [68]:
a.shape

(5, 4, 3, 2)

In [93]:
a = np.random.rand(4,4,5,4)

In [94]:
b = np.random.permutation(a)
print(np.argmax(b))

171


In [95]:
index = np.unravel_index(np.argmax(b),b.shape)
print(index)
print(b[index])

(2, 0, 2, 3)
0.9961358081796424


In [101]:
a = np.random.randint(0,20,(4))
print(a,'\n',np.gradient(a))

[18  0 16 14] 
 [-18.  -1.   7.  -2.]


In [103]:
c = np.random.randint(0,20,(4,5))
print('{}\n的梯度是\n{}'.format(c, np.gradient(c)))

[[10 19 15 15 11]
 [15 10  0  4 13]
 [10 11 19 17 10]
 [ 6  9  9  9 14]]
的梯度是
[array([[  5. ,  -9. , -15. , -11. ,   2. ],
       [  0. ,  -4. ,   2. ,   1. ,  -0.5],
       [ -4.5,  -0.5,   4.5,   2.5,   0.5],
       [ -4. ,  -2. , -10. ,  -8. ,   4. ]]), array([[ 9. ,  2.5, -2. , -2. , -4. ],
       [-5. , -7.5, -3. ,  6.5,  9. ],
       [ 1. ,  4.5,  3. , -4.5, -7. ],
       [ 3. ,  1.5,  0. ,  2.5,  5. ]])]
